import 'package:fir_client/constants.dart';
import 'package:fir_client/engine.dart';
import 'package:fir_client/loginPage.dart';
import 'package:flutter/material.dart';
import 'ratingWidget.dart';
import 'fastMatchingWidget.dart';
import 'previouseGamesWidget.dart';

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class MainPage extends StatelessWidget {
  const MainPage({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        appBar: AppBar(
            backgroundColor: Colors.blue,
            title: const Text("Welcome to Five-in-row!")),
        body: ListView(children: [
          const TopAppBar(),
          RatingWidget(),
          fastMatchingWidget(),
          PreviousGamesWidget()
        ]),
      ),
    );
  }
}

class TopAppBar extends StatelessWidget {
  const TopAppBar({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: double.infinity,
          height: 116,
          padding: const EdgeInsets.only(bottom: 24),
          decoration: BoxDecoration(color: MyColor.surface),
          child: Row(
            mainAxisSize: MainAxisSize.min,
            mainAxisAlignment: MainAxisAlignment.start,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              const SizedBox(width: 20),
              IconButton(
                  iconSize: 40,
                  onPressed: () {
                    Navigator.push(context,
                        MaterialPageRoute(builder: (context) => LoginPage()));
                  },
                  icon:
                      const Icon(Icons.person_2_outlined, color: Colors.black)),
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 16),
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    ValueListenableBuilder<Infos>(
                        valueListenable: Engine().notifier,
                        builder: (context, value, _) {
                          String text;
                          if (value.loginState == false) {
                            text = 'Hello, guest!';
                          } else {
                            text = 'Hello, ${value.userinfo.id}!';
                          }

                          return Text(
                            text,
                            style: TextStyle(color: MyColor.text, fontSize: 22),
                          );
                        })
                  ],
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
